FROM xebialabs/xl-release:23.1

# Install license
# COPY default-conf/xl-release-license.lic /opt/xebialabs/xl-release-server/default-conf/

# Install Docker runner plugin
ADD https://dist.xebialabs.com/public/maven2/com/xebialabs/xlrelease/plugins/xlr-docker-runner-plugin/0.1.4/xlr-docker-runner-plugin-0.1.4.jar /opt/xebialabs/xl-release-server/default-plugins/__local__